# Generated by Django 2.0.4 on 2018-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docclf', '0003_auto_20180502_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='actual_class',
            field=models.IntegerField(default=0),
        ),
    ]
